# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  

jobs:
  build-and-test:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Node.js server
        uses: actions/setup-node@v3
        with:
          node-version: 15.x
          
      - name: Install Node.js dependencies
        working-directory: ./MockServer
        run: npm install
        
      - name: Run Node.js server
        working-directory: ./MockServer
        run: |
            npm start &
            sleep 10 &&
            curl -X GET http://localhost:3000/data/2.5/weather
      
      - name: Build and Test
        working-directory: ./MyLibrary
        run: |
          swift build -v
          swift test -v
